CREATE TYPE [dbo].[OutputMembership_PartC_Inner] AS TABLE (
    [PmtYear]            INT             NOT NULL,
    [MemberID]           VARCHAR (50)    NOT NULL,
    [BirthDate_Org]      DATE            NOT NULL,
    [BirthDate]          DATE            NOT NULL,
    [Age]                INT             NOT NULL,
    [AgeBand]            VARCHAR (10)    NOT NULL,
    [Gender_Org]         VARCHAR (1)     NOT NULL,
    [Gender]             VARCHAR (1)     NOT NULL,
    [RAType_Org]         VARCHAR (10)    NOT NULL,
    [RAType]             VARCHAR (10)    NOT NULL,
    [RAType_Engine]      VARCHAR (10)    NOT NULL,
    [Hospice_Org]        VARCHAR (1)     NOT NULL,
    [Hospice]            VARCHAR (1)     NOT NULL,
    [LTIMCAID_Org]       VARCHAR (1)     NOT NULL,
    [LTIMCAID]           VARCHAR (1)     NOT NULL,
    [NEMCAID_Org]        VARCHAR (1)     NOT NULL,
    [NEMCAID]            VARCHAR (1)     NOT NULL,
    [OREC_Org]           VARCHAR (1)     NOT NULL,
    [OREC]               VARCHAR (1)     NOT NULL,
    [OriginallyDisabled] VARCHAR (1)     NOT NULL,
    [OriginallyESRD]     VARCHAR (1)     NOT NULL,
    [ra_variable]        VARCHAR (MAX)   NULL,
    [raf_demo]           NUMERIC (19, 3) NULL,
    [raf_demo_status]    NUMERIC (19, 3) NULL,
    [raf_dis]            NUMERIC (19, 3) NULL,
    [raf_dis_count]      NUMERIC (19, 3) NULL,
    [raf_dis_int_dis]    NUMERIC (19, 3) NULL,
    [raf_dis_int_disab]  NUMERIC (19, 3) NULL,
    [raf_total]          NUMERIC (19, 3) NULL,
    [Model]              VARCHAR (500)   NULL,
    [ClinicalVersion]    VARCHAR (500)   NULL,
    [Message]            VARCHAR (4000)  NULL);

