name: Deploy to SQL Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SQLCMD and SQL Server ODBC Driver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          # Install Microsoft ODBC Driver for SQL Server, mssql-tools, and unixodbc-dev
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools unixodbc-dev

      - name: Validate DB Connection
        env:
          SQL_SERVER: 135.237.13.78,1433
          SQL_DB: ramoduledev_deploy
          SQL_USER: etl_user
          SQL_PASSWORD: etl_user
        run: |
          set -e
          echo "Attempting to connect to SQL Server..."
          if /opt/mssql-tools/bin/sqlcmd -S "$SQL_SERVER" -d "$SQL_DB" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "SELECT 1" > connection.log 2>&1; then
            echo "✅ DB connection successful!"
          else
            echo "❌ DB connection failed!"
            echo "--- SQLCMD ERROR LOG ---"
            cat connection.log
            exit 1
          fi

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x' # or your required version

      - name: Build SQL project
        run: dotnet build ./raf_score_DB/raf_score_DB.sqlproj --configuration Release

      # Update the DACPAC_PATH to point to Release folder
      - name: Deploy DACPAC to SQL Server
        env:
          SQL_SERVER: 135.237.13.78,1433
          SQL_DB: ramoduledev_deploy
          SQL_USER: etl_user
          SQL_PASSWORD: etl_user
        run: |
          DACPAC_PATH=./raf_score_DB/bin/Release/raf_score_DB.dacpac
          /usr/local/bin/sqlpackage /Action:Publish /SourceFile:$DACPAC_PATH /TargetServerName:$SQL_SERVER /TargetDatabaseName:$SQL_DB /TargetUser:$SQL_USER /TargetPassword:$SQL_PASSWORD /Quiet
